[build]
  publish = "."

[[redirects]]
  from = "http://debarras-annecy.fr/*"
  to = "https://debarras-annecy.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.debarras-annecy.fr/*"
  to = "https://debarras-annecy.fr/:splat"
  status = 301
  force = true
